### ISSUE TITLE
Error In testing test_demo.py

### ISSUE THREAD

**Issue by ragavendranbala** [leimao/DeepLab_v3#5]
I got the Following Error while testing 

D:\Ragavendranbala\Image Processing\DeepLab_v3-master>python test_demo.py
Calculating pixel means for each channel of images...
0it [00:00, ?it/s]Traceback (most recent call last):
  File "test_demo.py", line 20, in <module>
    channel_means = save_load_means(means_filename='channel_means.npz', image_filenames=None)
  File "D:\Ragavendranbala\Image Processing\DeepLab_v3-master\utils.py", line 45, in save_load_means
    channel_means = image_channel_means(image_filenames=image_filenames)
  File "D:\Ragavendranbala\Image Processing\DeepLab_v3-master\utils.py", line 24, in image_channel_means
    for image_filename in tqdm(image_filenames):
  File "C:\Users\ragav\AppData\Local\Programs\Python\Python35\lib\site-packages\tqdm\_tqdm.py", line 937, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable

D:\Ragavendranbala\Image Processing\DeepLab_v3-master>

**Comment by leimao** [comment]
Will you be able to print out the variable "image_filenames"?

**Comment by ragavendranbala** [comment]
Don't know,I used only python test_demo.py command

**Comment by leimao** [comment]
I just tested the script on Ubuntu 16.04, and everything worked fine. I think this might be a compatibility issue with Windows, although I have never tested it on Windows previously.

To trouble shoot, first please make sure you have the latest version of tqdm installed. Then please modify the function "image_channel_means" in the script "utils.py" to print out the variable "image_filenames".

It would be something like this:
```
def image_channel_means(image_filenames):
    '''
    Calculate the means of RGB channels in image dataset.
    Support extremely large images of different sizes and arbitrarily large number of images.
    image_filenames: list of image filenames
    '''

    print(image_filenames)

    num_pixels = 0
    channel_sums = np.zeros(3, dtype=object)

    for image_filename in tqdm(image_filenames):
        image = cv2.imread(image_filename)
        channel_sums += np.sum(image, axis=(0, 1))
        num_pixels += np.prod(image.shape[:2])

    channel_means = (channel_sums / num_pixels).astype(float)

    return channel_means
```

We want to make sure that the variable "image_filenames" is still a list when you call this function.

If it turns out the variable "image_filenames" is indeed a list variable containing all the image filenames. This is highly likely that the tqdm package was not very compatible with Windows. Instead of using ``for image_filename in tqdm(image_filenames):``, please use ``for image_filename in image_filenames:``, you will lose progress bar though.

I apologize that I don't have Windows environment to troubleshoot it directly for you.

**Comment by ragavendranbala** [comment]
Will check and tell you soon

**Comment by leimao** [comment]
Thanks, I am also interested in knowing why this does not work on Windows.

**Comment by ragavendranbala** [comment]
Hi, I used you above code and got this 

D:\Ragavendranbala\Image Processing\DeepLab_v3-master>python test_demo.py
Calculating pixel means for each channel of images...
None
0it [00:00, ?it/s]Traceback (most recent call last):
  File "test_demo.py", line 20, in <module>
    channel_means = save_load_means(means_filename='channel_means.npz', image_filenames=None)
  File "D:\Ragavendranbala\Image Processing\DeepLab_v3-master\utils.py", line 47, in save_load_means
    channel_means = image_channel_means(image_filenames=image_filenames)
  File "D:\Ragavendranbala\Image Processing\DeepLab_v3-master\utils.py", line 26, in image_channel_means
    for image_filename in tqdm(image_filenames):
  File "C:\Users\ragav\AppData\Local\Programs\Python\Python35\lib\site-packages\tqdm\_tqdm.py", line 937, in __iter__
    for obj in iterable:
TypeError: 'NoneType' object is not iterable



tpdm =4.26.0

**Comment by ragavendranbala** [comment]
Used this

for image_filename in image_filenames:

and Got


D:\Ragavendranbala\Image Processing\DeepLab_v3-master>python test_demo.py
Calculating pixel means for each channel of images...
None
Traceback (most recent call last):
  File "test_demo.py", line 20, in <module>
    channel_means = save_load_means(means_filename='channel_means.npz', image_filenames=None)
  File "D:\Ragavendranbala\Image Processing\DeepLab_v3-master\utils.py", line 47, in save_load_means
    channel_means = image_channel_means(image_filenames=image_filenames)
  File "D:\Ragavendranbala\Image Processing\DeepLab_v3-master\utils.py", line 26, in image_channel_means
    for image_filename in image_filenames:
TypeError: 'NoneType' object is not iterable

**Comment by leimao** [comment]
I think I know what your problem is. I bet you did not train the model but direct ran the test_demo.py script. 

This will not work because the test_demo.py requires a file called channel_means.npz. This file will be generated during the data preprocessing/training time. Please double check if you have this file in your directory. 

Since we did not provide a pre-trained model, you will have to train the model first then run the test demo script.

**Comment by ragavendranbala** [comment]
Oh! First of all I have to train the model, then only, I have to run this script! Okay make sense.. I need to know how to train my own data which has labelled floor images. Can you share me a step by step guide to train my own model using xception or mobilenet?
Thanks in advance

**Comment by leimao** [comment]
I am probably not going through it myself, since it is not a program problem or issue. The basic instructions were in the README file. You are free to read and modify any code you want based on your own needs.

**Comment by ragavendranbala** [comment]
Okay thanks. Try to change the code. But I'm a beginner in python so only asked.

**Comment by leimao** [comment]
Yeah, I was in the same stage. Practice makes you better.

**Comment by ragavendranbala** [comment]
Thank you let's close this issue. And ping u of I faced anything again

**Comment by leimao** [comment]
You are welcome.
